services:
  dataset-api:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - path: .env
        required: false
    volumes:
      - ./policies:/app/policies:ro
    ports:
      - "8001:8001"
    depends_on:
      dataset-api-migrate:
        condition: service_completed_successfully
    healthcheck:
      test:
        [
          "CMD",
          "python3",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8001/health')",
        ]
      interval: 10s
      timeout: 3s
      retries: 5
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "keycloak.celine.localhost:host-gateway"
      - "api.celine.localhost:host-gateway"

  dataset-api-migrate:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: "no"
    env_file:
      - path: .env
        required: false
    entrypoint: ["/bin/sh"]
    command: alembic upgrade head
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "keycloak.celine.localhost:host-gateway"
      - "api.celine.localhost:host-gateway"

  dataset-api-import:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: "no"
    env_file:
      - path: .env
        required: false
    depends_on:
      dataset-api:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-euc"]
    command:
      - >
        # dataset-cli import catalogue --input "/app/data/openlineage/*.yaml" --api-url http://api.celine.localhost/datasets --verbose || true
        # dataset-cli import catalogue --input "/app/data/postgres/*.yaml" --api-url http://api.celine.localhost/datasets --verbose || true
        # directly load governance.yaml files and import
        dataset-cli export governance "/app/governance-pipelines/**/governance.yaml" -o /tmp/celine-pipelines --verbose
        dataset-cli import catalogue --input "/tmp/celine-pipelines/*.yaml" --api-url http://api.celine.localhost/datasets --verbose
    volumes:
      - ./data:/app/data:ro
      - ../celine-pipelines/apps:/app/governance-pipelines:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "keycloak.celine.localhost:host-gateway"
      - "api.celine.localhost:host-gateway"
