version: "3"

tasks:
  run:
    desc: "Run development server"
    cmds:
      - uv run uvicorn dataset.main:app --reload

  cli:export-lineage:
    desc: Export lineage from marquez
    cmds:
      - mkdir -p ./data/openlineage
      - uv run python -m dataset.cli.main export openlineage --ns '*' -o ./data/openlineage

  cli:import-datasets:
    desc: Import exported datasets to API catalogue
    cmds:
      - uv run python -m dataset.cli.main import catalogue -i "./data/openlineage/*.yaml" --api-url http://localhost:8000

  migrate:
    desc: "Run migrations"
    cmds:
      - uv run alembic upgrade head

  make-migration:
    desc: "Create new revision"
    cmds:
      - uv run alembic revision --autogenerate -m \"$MSG\"
    vars:
      MSG: "update"

  release:
    cmds:
      - uv run semantic-release -v version --no-vcs-release
      - git push
      - git push --tags
