version: "3"

tasks:
  run:
    desc: "Run development server"
    cmds:
      - uv run uvicorn celine.dataset.main:create_app --reload --host 0.0.0.0 --port 8001
  debug:
    desc: "Run development server with debugger"
    cmds:
      - DEBUG_ATTACH=nowait DEBUG_PORT=48001 .venv/bin/uvicorn celine.dataset.main:create_app --reload --host 0.0.0.0 --port 8001
  test:
    desc: "Run tests"
    cmds:
      - uv run pytest -- {{.CLI_ARGS}}

  cli:export:openlineage:
    desc: Export lineage from marquez
    cmds:
      - mkdir -p ./data/openlineage
      - uv run dataset-cli export openlineage --ns '*' -o ./data/openlineage --expose
  cli:export:postgres:
    desc: Export lineage from marquez
    cmds:
      - mkdir -p ./data/openlineage
      - uv run dataset-cli export postgres -o ./data/postgres --expose --tables 'ds_dev_gold.*' --namespace 'ds_dev_gold'

  cli:import-datasets:
    desc: Import exported datasets to API catalogue
    cmds:
      - uv run dataset-cli import catalogue --input "./data/openlineage/*.yaml" --api-url http://localhost:8001 --verbose || true
      - uv run dataset-cli import catalogue --input ./data/postgres/*.yaml --api-url http://localhost:8001 --verbose || true

  alembic:migrate:
    desc: "Run migrations"
    cmds:
      - uv run alembic upgrade head

  alembic:sync-model:
    desc: "Create new revision"
    cmds:
      - uv run alembic revision --autogenerate -m \"$MSG\"
    vars:
      MSG: "update model"

  alembic:reset:
    desc: "Reset DB schema"
    cmds:
      - uv run alembic downgrade base

  release:
    cmds:
      - uv run semantic-release -v version --no-vcs-release
      - git push
      - git push --tags
