version: "3"

tasks:
  run:
    desc: "Run development server"
    cmds:
      - uv run uvicorn dataset.main:app --reload

  migrate:
    desc: "Run migrations"
    cmds:
      - uv run alembic upgrade head

  make-migration:
    desc: "Create new revision"
    cmds:
      - uv run alembic revision --autogenerate -m \"$MSG\"
    vars:
      MSG: "update"
