version: "3"

tasks:
  run:
    desc: "Run development server"
    cmds:
      - uv run uvicorn celine.dataset.main:create_app --reload --host 0.0.0.0 --port 8001
  debug:
    desc: "Run development server with debugger"
    cmds:
      - DEBUG_ATTACH=nowait DEBUG_PORT=48001 uv run uvicorn celine.dataset.main:create_app --reload --host 0.0.0.0 --port 8001
  test:
    desc: "Run tests"
    cmds:
      - uv run pytest -- {{.CLI_ARGS}}

  cli:export-lineage:
    desc: Export lineage from marquez
    cmds:
      - mkdir -p ./data/openlineage
      - uv run python -m celine.dataset.cli.main export openlineage --ns '*' -o ./data/openlineage --expose

  cli:import-datasets:
    desc: Import exported datasets to API catalogue
    cmds:
      - uv run python -m celine.dataset.cli.main import catalogue -i "./data/openlineage/*.yaml" --api-url http://localhost:8001

  cli:ontology-fetch:
    desc: Fetch ontologies
    cmds:
      - uv run python -m celine.dataset.cli.main ontology fetch -o ./data/ontologies

  cli:ontology-analyze:
    desc: Fetch ontologies
    cmds:
      - uv run python -m celine.dataset.cli.main ontology analyze -- {{.CLI_ARGS}}

  cli:ontology-view:
    desc: View ontologies (requires xdot)
    cmds:
      - xdot data/ontologies/ontology-graph.dot

  alembic:migrate:
    desc: "Run migrations"
    cmds:
      - uv run alembic upgrade head

  alembic:sync-model:
    desc: "Create new revision"
    cmds:
      - uv run alembic revision --autogenerate -m \"$MSG\"
    vars:
      MSG: "update model"

  alembic:reset:
    desc: "Reset DB schema"
    cmds:
      - uv run alembic downgrade base

  release:
    cmds:
      - uv run semantic-release -v version --no-vcs-release
      - git push
      - git push --tags
